add_positions: true
epochs: 20
batch_size: 16
dev: ../fula_nltk.txt
dropout: 0.01
embedding_dims: 512
normalize_word_embeddings: false
radius: 4
tied_embeddings: false
ff_size: 2048
heads: 8
layers: 8
lr: 2.5e-4
max_lr: 0.01
max_length: 200
pad_idx: 3
tokenizer: data/tokenizers/fula_nltk_16000.model
train: ../fula_nltk.txt
gradients_accumulation: 256
vocab_size: 16000
valid_every_n_batchs: 3000
step_size_up: 2000
checkpoint: checkpoints/fula.pt