add_positions: true
epochs: 5
batch_size: 32
dev: data/raw_text/fula_nltk.txt
dropout: 0.1
embedding_dims: 256
ff_size: 1024
heads: 4
layers: 8
lr: 2.5e-4
max_lr: 0.01
max_length: 200
pad_idx: 3
tokenizer: data/tokenizers/fula_nltk_16000.model
train: data/raw_text/fula_nltk.txt
gradients_accumulation: 256
vocab_size: 16000
valid_every_n_batchs: 3000
step_size_up: 2000
checkpoint: 